import type { GlazeLibraryItem, GlazeTestTile } from './types';

const today = new Date().toISOString();

export const INITIAL_GLAZES: GlazeLibraryItem[] = [
  {
    id: 'glaze-satin-blue',
    name: 'Quiet Satin Blue',
    finish: 'satin',
    colorFamily: 'Blue Grey',
    coneRange: 'Cone 5-6',
    defaultCone: 'Cone 6',
    source: 'custom',
    notes: 'Breaks warmer on buff stoneware and cools off on porcelain.',
    applicationNotes: 'Usually happiest with a medium dip and a slow cool.',
    supplier: 'Studio Mix',
    batchSize: '5000 g dry batch',
    recipeNotes: 'Best sieve was 80 mesh. Keep water slightly thinner than usual.',
    recipeIngredients: [
      { id: 'qsb-1', material: 'Nepheline Syenite', percentage: '34' },
      { id: 'qsb-2', material: 'Silica', percentage: '24' },
      { id: 'qsb-3', material: 'Whiting', percentage: '14' },
      { id: 'qsb-4', material: 'EPK', percentage: '14' },
      { id: 'qsb-5', material: 'Rutile', percentage: '6' },
      { id: 'qsb-6', material: 'Cobalt Carb', percentage: '0.7' },
    ],
    tags: ['satin', 'blue', 'cone 6'],
    collections: ['Production', 'Winter Glazes'],
    favorite: true,
    production: true,
    testTilePhotoUris: [],
    finishedPiecePhotoUris: [],
    accidentPhotoUris: [],
    clayBodiesUsed: ['Stoneware', 'Porcelain'],
    kilnTypesUsed: ['Electric'],
    conesTested: ['Cone 6'],
    createdAt: today,
    lastTestedAt: '2026-02-28T14:00:00.000Z',
  },
  {
    id: 'glaze-iron-honey',
    name: 'Iron Honey Matte',
    finish: 'matte',
    colorFamily: 'Honey Brown',
    coneRange: 'Cone 6',
    defaultCone: 'Cone 6',
    source: 'store-bought',
    notes: 'Lovely on speckled bodies, but can drift green if too thick.',
    applicationNotes: 'Better when brushed in three thin coats than dunked heavy.',
    supplier: 'Mayco',
    batchSize: 'Pint',
    recipeNotes: '',
    recipeIngredients: [],
    tags: ['matte', 'iron', 'production'],
    collections: ['Favorites'],
    favorite: false,
    production: false,
    testTilePhotoUris: [],
    finishedPiecePhotoUris: [],
    accidentPhotoUris: [],
    clayBodiesUsed: ['Speckled Buff', 'Stoneware'],
    kilnTypesUsed: ['Electric'],
    conesTested: ['Cone 5', 'Cone 6'],
    createdAt: today,
    lastTestedAt: '2026-01-19T11:30:00.000Z',
  },
  {
    id: 'glaze-crystal-mint',
    name: 'Crystal Mint Runny',
    finish: 'crystalline',
    colorFamily: 'Mint Green',
    coneRange: 'Cone 6',
    defaultCone: 'Cone 6',
    source: 'custom',
    notes: 'Beautiful with thick overlap. Also responsible for two kiln cookies and one shelf grind session.',
    applicationNotes: 'Needs cookies. Do not trust it near the foot.',
    supplier: 'Studio Mix',
    batchSize: '1000 g test batch',
    recipeNotes: 'Trying zinc variations. Still in chaos mode.',
    recipeIngredients: [
      { id: 'cmr-1', material: 'Frit 3110', percentage: '28' },
      { id: 'cmr-2', material: 'Zinc Oxide', percentage: '18' },
      { id: 'cmr-3', material: 'Silica', percentage: '24' },
      { id: 'cmr-4', material: 'Kaolin', percentage: '12' },
      { id: 'cmr-5', material: 'Copper Carb', percentage: '1.2' },
    ],
    tags: ['experimental', 'crystals', 'runny'],
    collections: ['Experiments'],
    favorite: true,
    production: false,
    testTilePhotoUris: [],
    finishedPiecePhotoUris: [],
    accidentPhotoUris: [],
    clayBodiesUsed: ['Porcelain'],
    kilnTypesUsed: ['Electric'],
    conesTested: ['Cone 6'],
    createdAt: today,
    lastTestedAt: '2025-12-04T09:15:00.000Z',
  },
];

export const INITIAL_GLAZE_TESTS: GlazeTestTile[] = [
  {
    id: 'test-quiet-blue-1',
    glazeId: 'glaze-satin-blue',
    glazeNameSnapshot: 'Quiet Satin Blue',
    clayBody: 'Stoneware',
    cone: 'Cone 6',
    kilnName: 'North Skutt',
    kilnType: 'electric',
    applicationMethod: 'dip',
    thickness: 'medium',
    layeredWith: [],
    shelfPosition: 'Middle shelf',
    firingDate: '2026-02-28T14:00:00.000Z',
    notes: 'Soft blue with warm breaks on the rim. Stable and dependable.',
    resultRating: 'great',
    defects: [],
  },
  {
    id: 'test-iron-honey-1',
    glazeId: 'glaze-iron-honey',
    glazeNameSnapshot: 'Iron Honey Matte',
    clayBody: 'Speckled Buff',
    cone: 'Cone 6',
    kilnName: 'North Skutt',
    kilnType: 'electric',
    applicationMethod: 'brush',
    thickness: 'medium',
    layeredWith: [],
    shelfPosition: 'Bottom shelf',
    firingDate: '2026-01-19T11:30:00.000Z',
    notes: 'Great honey surface, slight green shift where it pooled.',
    resultRating: 'interesting',
    defects: ['color-shift'],
  },
  {
    id: 'test-crystal-mint-1',
    glazeId: 'glaze-crystal-mint',
    glazeNameSnapshot: 'Crystal Mint Runny',
    clayBody: 'Porcelain',
    cone: 'Cone 6',
    kilnName: 'North Skutt',
    kilnType: 'electric',
    applicationMethod: 'pour',
    thickness: 'thick',
    layeredWith: ['Clear Liner'],
    shelfPosition: 'Top shelf',
    firingDate: '2025-12-04T09:15:00.000Z',
    notes: 'Beautiful crystals, but it ran hard and needed a cookie.',
    resultRating: 'interesting',
    defects: ['running'],
  },
  {
    id: 'test-quiet-blue-2',
    glazeId: 'glaze-satin-blue',
    glazeNameSnapshot: 'Quiet Satin Blue',
    clayBody: 'Porcelain',
    cone: 'Cone 6',
    kilnName: 'North Skutt',
    kilnType: 'electric',
    applicationMethod: 'spray',
    thickness: 'thin',
    layeredWith: [],
    shelfPosition: 'Top shelf',
    firingDate: '2025-11-18T15:20:00.000Z',
    notes: 'Much cooler blue, more matte than satin, very even surface.',
    resultRating: 'great',
    defects: [],
  },
];