import {
    BriefcaseBusiness,
    Building2,
    Hammer,
    HelpCircle,
    Home,
    Layers,
    Users,
} from 'lucide-react-native';
import { OnboardingUserType, StepKey, UserTypeConfig } from "../types/user";

export const USER_TYPE_CONFIG: Record<OnboardingUserType, UserTypeConfig> = {
    'home-potter': {
        label: 'Home Potter',
        description: 'You mostly create at home and may use your own kiln or a kiln service.',
        help: 'Great for personal practice with light operations.',
        practiceMode: 'home',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library'],
        pricingUserType: 'hobby',
        includeHomeSetup: true,
        icon: Home,
    },
    'studio-potter': {
        label: 'Studio Potter',
        description: 'You mainly work in a shared studio environment.',
        help: 'Keeps tools focused on studio flow and shared firing context.',
        practiceMode: 'studio',
        role: 'member',
        defaultModules: ['overview', 'pieces', 'kiln', 'library', 'community'],
        pricingUserType: 'side-business',
        includeHomeSetup: false,
        icon: Building2,
    },
    'hybrid-potter': {
        label: 'Hybrid Potter',
        description: 'You split your practice between home and studio spaces.',
        help: 'Best balanced setup for mixed workflows.',
        practiceMode: 'both',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library', 'community'],
        pricingUserType: 'side-business',
        includeHomeSetup: true,
        icon: Layers,
    },
    'studio-owner-technician': {
        label: 'Studio Owner / Technician',
        description: 'You run kilns, monitor firing consistency, and support members.',
        help: 'Uses a fuller operational setup with kiln-first defaults.',
        practiceMode: 'studio',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library', 'community'],
        pricingUserType: 'full-time',
        includeHomeSetup: false,
        icon: Hammer,
    },
    teacher: {
        label: 'Teacher / Instructor',
        description: 'You coordinate lessons, demos, and student progress.',
        help: 'Keeps your flow structured and easy to revisit.',
        practiceMode: 'studio',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library'],
        pricingUserType: 'side-business',
        includeHomeSetup: false,
        icon: Users,
    },
    'business-owner': {
        label: 'Small Business Owner',
        description: 'You create for sales, planning, and production consistency.',
        help: 'Enables fuller workflow defaults for sustainable operations.',
        practiceMode: 'both',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library', 'community'],
        pricingUserType: 'full-time',
        includeHomeSetup: false,
        icon: BriefcaseBusiness,
    },
    'not-sure': {
        label: 'I’m Not Sure Yet',
        description: 'Start with a balanced setup and refine later in settings.',
        help: 'You can adjust role and modules at any time.',
        practiceMode: 'both',
        role: 'owner',
        defaultModules: ['overview', 'pieces', 'kiln', 'library', 'community'],
        pricingUserType: 'side-business',
        includeHomeSetup: false,
        icon: HelpCircle,
    },
};

export const headingByStep: Record<StepKey, string> = {
    welcome: 'Welcome to your cozy pottery companion',
    role: 'Who are you in your pottery practice?',
    pricing: 'Choose your pricing starting point',
    kiln: 'Kiln setup and studio context',
    kilnkin: 'Choose your Kilnkin companion',
    'home-setup': 'Optional home studio setup',
    routines: 'Set your pottery rhythm',
    preferences: 'Personal preferences and modules',
    'studio-preview': 'Quick studio / home overview',
    ready: 'Ready to create',
};

export const subheadingByStep: Record<StepKey, string> = {
    welcome: 'Track, create, and celebrate every piece with calm guidance and playful support.',
    role: 'Your role helps tailor modules and defaults so the app feels focused from day one.',
    pricing: 'Pick the pricing profile that best matches how you make and sell right now.',
    kiln: 'Add what you know now, skip what you can decide later.',
    kilnkin: 'Pick the companion that matches your studio energy.',
    'home-setup': 'A few optional notes can make your home workflow smoother.',
    routines: 'Start simple. You can update goals and cadence in settings.',
    preferences: 'Choose units, language, reminders, and what modules are visible.',
    'studio-preview': 'A mini orientation before entering your full studio view.',
    ready: 'Your Kilnkin and studio are ready. Let’s begin your next piece.',
};